### ISSUE TITLE
Some questions about turbulence simulators.

### ISSUE THREAD

**Issue by jcy512** [xg416/DATUM#7]
Dear authors,

I noticed that the dataset used in this article was generated by your fourth and fifth versions of the turbulence simulator. However, on your website, only the second version of the simulator code is available. I would like to ask if there is any plan to make the fourth and fifth versions of the simulator code publicly available.

Thank you for your attention to this matter. I look forward to your reply.

**Comment by xg416** [comment]
This is version 5 based on our internal convention. We do not have such plans because the simulator is protected by a patent under Purdue's regularization. If you want to get the simulator, you can contact Dr. Chan directly, making your advisor or organization involved will increase the possibility of getting his approval.
I may release a much faster simulator with more approximation later, however, this depends on the next paper.

**Comment by jcy512** [comment]
Thank you for your response. Regarding the PIRN dataset that you mentioned in your answer to question 4, I would appreciate it if you could send me a copy. My email address is [jiaochunyang68@gmail.com](mailto:jiaochunyang68@gmail.com).

**Comment by xg416** [comment]
This is what Ajay replied:
Please find GT images and the turbulence simulator parameters used to generate PiRN synthetic data here at https://app.box.com/s/njcngbxvfrhy476fdjpkwmfozo71twpu.
To save the noise seed, use the parameter values available in the above link here https://github.com/VITA-Group/PiRN/blob/12b9ef6a32c75143c23402a7ab8f843624ca99e8/assets/generate-data.py#L23
