### ISSUE TITLE
Dataset-related questions

### ISSUE THREAD

**Issue by jcy512** [xg416/DATUM#8]
Dear authors,

I am deeply impressed by the work your laboratory has done in the area of turbulence image clarification. After reviewing some of your recent papers, I am particularly interested in the single-frame turbulence image de-turbulence technique. However, I am struggling to find a large-scale dataset for training purposes. Would it be possible for you to provide a paired single-frame turbulence image dataset from TurbNet or PiRN? We would greatly appreciate it if we could use this dataset for our research purposes.If I am able to obtain the dataset you provide for training purposes, I assure you that the dataset will only be used to train our model and will not be used for commercial purposes.

Thank you in advance for your kind consideration.

**Comment by jcy512** [comment]
If I am able to obtain the dataset you provide for training purposes, I assure you that the dataset will only be used to train our model and will not be used for commercial purposes.

**Comment by xg416** [comment]
Hi, you can take a look at the github repo of TurbNet, the dataset are public. 
For PiRN, Please find the turbulence simulator parameters used to generate PiRN synthetic data here at [https://app.box.com/s/njcngbxvfrhy476fdjpkwmfozo71twpu](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.box.com%2Fs%2Fnjcngbxvfrhy476fdjpkwmfozo71twpu&data=05%7C02%7Czhan3275%40purdue.edu%7Cd3c14e4da8014279284f08dc5bead40b%7C4130bd397c53419cb1e58758d6d63f21%7C0%7C0%7C638486311352329828%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=Apz5HgN1AY7mrRhGrU9%2F1zcfZ4mIkLbkMCmD%2BDXmNYc%3D&reserved=0). 
To save the noise seed, use the parameter values available in the above link over here [[line](https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVITA-Group%2FPiRN%2Fblob%2F12b9ef6a32c75143c23402a7ab8f843624ca99e8%2Fassets%2Fgenerate-data.py%23L23&data=05%7C02%7Czhan3275%40purdue.edu%7Cd3c14e4da8014279284f08dc5bead40b%7C4130bd397c53419cb1e58758d6d63f21%7C0%7C0%7C638486311352342141%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=q%2BZ5D20QtUXFBCSQlGeEHpoGrbI6cNKHXCNwLDtf8kk%3D&reserved=0)].

And you can also use our ATSyn dataset for single-frame turbulence mitigation as well, the domain gap is small because the data synthesis methods are pretty similar
